"""add pending_turn_approvals

Revision ID: 2b1bb177b154
Revises: b2c3d4e5f6a7
Create Date: 2026-09-19 11:38:18.909957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1bb177b154'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_turn_approvals',
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('sub_agent_id', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('tool_use_id', sa.String(length=128), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('guard_snapshot', sa.JSON(), nullable=False),
    sa.Column('completed_results', sa.JSON(), nullable=False),
    sa.Column('remaining_sub_agent_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sub_agent_id'], ['sub_agents.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('turn_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_turn_approvals')
    # ### end Alembic commands ###
