"""add turn_verifications and sub_agent_model_overrides

Revision ID: 6fd1a76f89ab
Revises: a1b2c3d4e5f6
Create Date: 2026-09-19 08:32:43.951794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd1a76f89ab'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_agent_model_overrides',
    sa.Column('sub_agent_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('set_by_user_id', sa.UUID(), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sub_agent_id'], ['sub_agents.id'], ),
    sa.PrimaryKeyConstraint('sub_agent_id')
    )
    op.create_table('turn_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('galileo_trace_id', sa.String(length=128), nullable=True),
    sa.Column('invoked_by_user_id', sa.UUID(), nullable=False),
    sa.Column('invoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn_verifications')
    op.drop_table('sub_agent_model_overrides')
    # ### end Alembic commands ###
